
logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.dxc.eproc.estimate: DEBUG
    
#Spring Starts
spring:
  profiles: prod
  devtools:
    restart:
      enabled: false
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    #driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
    #dbcp2:
      #test-on-borrow: true
  transaction:
    default-timeout: 120    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.connection.provider_disables_autocommit: true
        #hibernate.cache.use_second_level_cache: true
        #hibernate.cache.use_query_cache: false
        #hibernate.generate_statistics: false
      #hibernate.hbm2ddl.auto: update
#Spring Ends

server:
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

opentracing:
  jaeger:
    expand-exception-logs: false
    udp-sender:
      host: 130.175.175.137
      port: 6831
    enabled: false
    enable-b3-propagation: false
    log-spans: false
    const-sampler:
      decision: false
  
#eProcurement Properties Starts
eprocurement:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${eprocurement.clientApp.name}-alert,X-${eprocurement.clientApp.name}-error,X-${eprocurement.clientApp.name}-params'
    allow-credentials: false
    max-age: 1800
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  mail: # specific Eprocurement mail property, for standard properties see MailProperties
    base-url: http://130.175.175.137:3000/supplier/supplier-registration/verify-otp?key=
    jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: YmVlMjVlNGQ0ZGE5ZThmNTQ3YjA5YzcyOTU1NTRmYTA2ZmIxYmQxZjYzMTUxNTE0MzZlODU4OTI2MTk0YTcxZWUxYzI2OWNlYTE0NzFhODg2ZTA4ODMwNjliZDU2ZjYxZjZlN2UzNWI4ZWY0YTZlYmJjZDE2MWZhZjUxNjRkNzE=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000    
      
# Feign Client Starts
kie-server-service:
  url: http://130.175.175.137:9194/rest 
pki-service:
  url: http://130.175.175.137:9192 
