package com.dxc.eproc.estimate.enumeration;

public enum WorkType {
	ORIGINAL, IMPROVEMENT, MAINTENANCE, RESTORATION, SPECIALREPAIRS ,CLOSUREPERIODWORKS, REPAIRS, TURNKEYWORKS, LABOURCONTRACTWORKS, SUPPLYANDERECTION
}
